#!/usr/bin/env python3
"""Download the flamapy-authored wheels from the flamapy GitHub release bundle.

Each ``flamapy/flamapy`` release attaches a ``flamapy-wheels-<tag>.zip`` asset
containing the pure-python wheels of the flamapy-authored packages (``flamapy_fw``,
``flamapy_fm``, ``flamapy``, ``flamapy_sat``, ``flamapy_bdd``, ``flamapy_z3``). This
resolves the version pinned in ``flamapy.version``, downloads that bundle and unpacks
its wheels into ``public/flamapy/`` — so the flamapy wheels come from the GitHub
release, not PyPI.

It intentionally does *not* fetch the third-party dependency wheels (uvlparser, ply,
dd, …): those are not in the bundle and are downloaded from PyPI by ``make
build-wheels``. It also does not write ``plugins.conf.json`` — that is generated by
``scripts/generate_plugins_manifest.py`` after all wheels are on disk.

Environment:
    FLAMAPY_REPO          release repo (default: flamapy/flamapy)
    FLAMAPY_WHEELS_DIR    output dir (default: public/flamapy)
    FLAMAPY_VERSION       overrides ./flamapy.version
    FLAMAPY_VERSION_FILE  version file path (default: flamapy.version)
    GITHUB_TOKEN          optional; raises the GitHub API rate limit
"""
# Lazy annotations so the PEP 604 "X | None" hints below don't get evaluated at
# runtime on Python 3.9 (still the default `python3` on stock macOS), keeping
# `make build-wheels` working locally as well as on the 3.11 CI/Docker images.
from __future__ import annotations

import io
import json
import os
import sys
import urllib.error
import urllib.request
import zipfile
from pathlib import Path

REPO = os.environ.get("FLAMAPY_REPO", "flamapy/flamapy")
WHEELS_DIR = Path(os.environ.get("FLAMAPY_WHEELS_DIR", "public/flamapy"))
VERSION_FILE = Path(os.environ.get("FLAMAPY_VERSION_FILE", "flamapy.version"))
USER_AGENT = "flamapy-ide-wheel-updater"


def resolve_version() -> str:
    """The flamapy version to pull, from $FLAMAPY_VERSION or ./flamapy.version.

    Returns a version string (e.g. "2.6.0") or the sentinel "latest". Blank lines and
    ``#`` comments in the file are ignored; the first real line wins.
    """
    env = os.environ.get("FLAMAPY_VERSION")
    if env and env.strip():
        return env.strip()
    if VERSION_FILE.is_file():
        for raw in VERSION_FILE.read_text().splitlines():
            line = raw.split("#", 1)[0].strip()
            if line:
                return line
    return "latest"


def _request(url: str, accept: str | None = None) -> urllib.request.Request:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    if accept:
        req.add_header("Accept", accept)
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    return req


def _get_release(version: str) -> dict:
    """Fetch the GitHub release JSON for ``version`` ("latest" or e.g. "2.6.0").

    For a pinned version the release tag may be spelled ``2.6.0`` or ``v2.6.0``; both
    are tried before giving up.
    """
    accept = "application/vnd.github+json"
    if version == "latest":
        api = f"https://api.github.com/repos/{REPO}/releases/latest"
        with urllib.request.urlopen(_request(api, accept)) as resp:
            return json.load(resp)

    last_error: Exception | None = None
    for tag in (version, f"v{version}"):
        api = f"https://api.github.com/repos/{REPO}/releases/tags/{tag}"
        try:
            with urllib.request.urlopen(_request(api, accept)) as resp:
                return json.load(resp)
        except urllib.error.HTTPError as exc:  # 404 -> try the next spelling
            last_error = exc
            if exc.code != 404:
                raise
    raise SystemExit(
        f"No release of {REPO} found for version '{version}' "
        f"(tried tags '{version}' and 'v{version}'). {last_error}"
    )


def fetch_bundle(version: str) -> tuple[str, bytes]:
    """Return (tag, zip_bytes) for the requested flamapy release bundle."""
    release = _get_release(version)
    tag = release["tag_name"]

    assets = release.get("assets", [])
    asset = next((a for a in assets if a["name"] == f"flamapy-wheels-{tag}.zip"), None)
    if asset is None:  # be lenient about the exact tag spelling in the filename
        asset = next(
            (a for a in assets if a["name"].startswith("flamapy-wheels-")
             and a["name"].endswith(".zip")),
            None,
        )
    if asset is None:
        raise SystemExit(
            f"Release {tag} of {REPO} has no 'flamapy-wheels-*.zip' asset. "
            "Nothing to download."
        )

    with urllib.request.urlopen(_request(asset["browser_download_url"])) as resp:
        return tag, resp.read()


def _distribution(wheel_filename: str) -> str:
    """The distribution name part of a wheel filename (e.g. 'flamapy_fw')."""
    return wheel_filename.split("-", 1)[0]


def extract_bundle(zip_bytes: bytes) -> list[str]:
    """Extract the bundle's wheels into WHEELS_DIR, returning the filenames written.

    Any wheel already present for the same distribution is removed first, so a version
    change (e.g. a stale ``…dev12`` next to ``…2.6.0``) can't linger and confuse the
    manifest generator's "newest wins" resolution.
    """
    WHEELS_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as bundle:
        wheels = [n for n in bundle.namelist() if n.endswith(".whl")]
        if not wheels:
            raise SystemExit("Bundle contains no wheels.")

        written: list[str] = []
        for member in wheels:
            name = os.path.basename(member)
            distribution = _distribution(name)
            for stale in WHEELS_DIR.glob(f"{distribution}-*.whl"):
                if stale.name != name:
                    stale.unlink()
            (WHEELS_DIR / name).write_bytes(bundle.read(member))
            written.append(name)
    return written


def main() -> int:
    version = resolve_version()
    print(f"Pinned flamapy version: {version}")
    tag, zip_bytes = fetch_bundle(version)
    written = extract_bundle(zip_bytes)
    print(f"Downloaded {len(written)} flamapy wheel(s) from {REPO} release {tag}:")
    for name in sorted(written):
        print(f"  {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
