name: Docker Image CI/CD

# Trigger the workflow when a tag is pushed
on:
  push:
    tags:
      - v**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag frabenrui/flamapy-ide:${{ github.ref_name }}

      # Step 3: Login to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      # Step 4: Push the Docker image to DockerHub
      - name: Push the Docker image
        run: docker push frabenrui/flamapy-ide:${{ github.ref_name }}

      # Optional: Step 5: Push the "latest" tag (for production deployments)
      - name: Tag as latest
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag frabenrui/flamapy-ide:${{ github.ref_name }} frabenrui/flamapy-ide:latest
          docker push frabenrui/flamapy-ide:latest
