name: Docker Image & deploy

on:
  workflow_run:
    workflows: [release-please]
    types: [completed]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag frabenrui/flamapy-ide:${{ github.ref_name }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      - name: Push the Docker image
        run: docker push frabenrui/flamapy-ide:${{ github.ref_name }}

      - name: Tag as latest
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag frabenrui/flamapy-ide:${{ github.ref_name }} frabenrui/flamapy-ide:latest
          docker push frabenrui/flamapy-ide:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        env:
          deploy_url: ${{secrets.RENDER_DEPLOY_HOOK_URL}}
        run: |
          curl "$deploy_url"
